## Task 1

In [1]:
import pandas as pd 
import numpy as np 

cars_df = pd.read_csv('cars.csv')

In [2]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

Horsepower is an object but should be numeric.  
Origin is int, but should be categorical.

## Task 2 Clean the Data

In [3]:
cars_df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [4]:
X= cars_df.loc[:, 'cylinders':'origin']
y= cars_df['mpg']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state=42)

In [6]:
X_train['horsepower'] = pd.to_numeric(X_train['horsepower'], errors='coerce')
X_test['horsepower'] = pd.to_numeric(X_test['horsepower'], errors='coerce')

In [7]:
hp_med = X_train['horsepower'].median()
X_train['horsepower']= X_train['horsepower'].fillna(hp_med)
X_test['horsepower']= X_test['horsepower'].fillna(hp_med)

## Task 3 Decide What Goes In and What Stays Out

We split prior to cleaning the horsepower column above.  
We cannot use car name because they are individual string values and would not serve well as categorical or numeric columns

## Task 4 When Should you split?

We split our data prior to cleaning the horsepower column to avoid data leakage when filling with the median value. If we had used the entire data set median, this would provide information about the data in the test set.  
The same concept would apply to scaling.

## Task 5 Encode the Categorical Column

In [8]:
categorical_cols = ['origin', 'model year', 'cylinders']
numeric_cols = ['displacement']

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ohe= OneHotEncoder(sparse_output=False, drop='first') # This satisfies question 6
origin_array= ohe.fit_transform(X_train[['origin']])
# get column names from sklearn
origin_cols= ohe.get_feature_names_out(['origin'])
# build df from array
df_origin = pd.DataFrame(origin_array, columns=origin_cols, dtype=int)
df1=pd.concat([X_train.drop(columns=['origin']).reset_index(), df_origin], axis=1)
print(df1.to_string())

     index  cylinders  displacement  horsepower  weight  acceleration  model year  origin_2  origin_3
0        3          8         304.0       150.0    3433          12.0          70         0         0
1       18          4          97.0        88.0    2130          14.5          70         0         1
2      376          4          91.0        68.0    2025          18.2          82         0         1
3      248          4          91.0        60.0    1800          16.4          78         0         1
4      177          4         115.0        95.0    2694          15.0          75         1         0
5       63          8         400.0       175.0    4385          12.0          72         0         0
6      246          4          78.0        52.0    1985          19.4          78         0         1
7      352          4          98.0        65.0    2380          20.7          81         0         0
8      108          4          97.0        88.0    2279          19.0          73         0         1
9       90          8         429.0       198.0    4952          11.5          73         0         0
10     231          8         400.0       190.0    4325          12.2          77         0         0
11     334          3          70.0       100.0    2420          12.5          80         0         1
12     118          4         116.0        75.0    2158          15.5          73         1         0
13     218          4          79.0        58.0    1825          18.6          77         1         0
14     210          6         156.0       108.0    2930          15.5          76         0         1
15     378          4         105.0        63.0    2125          14.7          82         0         0
16     371          4         135.0        84.0    2525          16.0          82         0         0
17     280          6         231.0       115.0    3245          15.4          79         0         0
18     323          4         156.0       105.0    2800          14.4          80         0         0
19      75          8         318.0       150.0    4077          14.0          72         0         0
20     245          4          98.0        66.0    1800          14.4          78         0         0
21     110          4         108.0        94.0    2379          16.5          73         0         1
22      16          6         199.0        97.0    2774          15.5          70         0         0
23      66          8         304.0       150.0    3672          11.5          72         0         0
24     153          6         250.0       105.0    3459          16.0          75         0         0
25       7          8         440.0       215.0    4312           8.5          70         0         0
26      19          4          97.0        46.0    1835          20.5          70         1         0
27     137          8         350.0       150.0    4699          14.5          74         0         0
28     353          4         105.0        74.0    2190          14.2          81         1         0
29     347          4          85.0        65.0    1975          19.4          81         0         1
30     131          4          71.0        65.0    1836          21.0          74         0         1
31     182          4         107.0        86.0    2464          15.5          76         1         0
32     291          8         267.0       125.0    3605          15.0          79         0         0
33     384          4          91.0        67.0    1965          15.7          82         0         1
34     296          4         121.0        80.0    2670          15.0          79         0         0
35      60          4         140.0        90.0    2408          19.5          72         0         0
36      79          4          96.0        69.0    2189          18.0          72         1         0
37     284          6         225.0       110.0    3360          16.6          79         0         0
38     304          4          91.0        69.0    2130          14.7          79         1         0
39     277          6         163.0       133.0    3410          15.8          78         1         0
40     157          8         350.0       145.0    4440          14.0          75         0         0
41     109          4         140.0        72.0    2401          19.5          73         0         0
42      17          6         200.0        85.0    2587          16.0          70         0         0
43     253          6         200.0        95.0    3155          18.2          78         0         0
44      24          6         199.0        90.0    2648          15.0          70         0         0
45     361          6         168.0       116.0    2900          12.6          81         0         1
46     349          4          91.0        68.0    1985          16.0          81         0         1
47     392          4         151.0        90.0    2950          17.3          82         0         0
48     379          4          98.0        70.0    2125          17.3          82         0         0
49     358          4         120.0        74.0    2635          18.3          81         0         1
50     310          4          89.0        60.0    1968          18.8          80         0         1
51     145          4          83.0        61.0    2003          19.0          74         0         1
52     324          4          85.0        65.0    2110          19.2          80         0         1
53     176          6         232.0        90.0    3211          17.0          75         0         0
54     119          4         114.0        91.0    2582          14.0          73         1         0
55     192          6         250.0       105.0    3353          14.5          76         0         0
56     202          6         258.0        95.0    3193          17.8          76         0         0
57     345          4          81.0        60.0    1760          16.1          81         0         1
58     237          4          98.0        63.0    2051          17.0          77         0         0
59     355          4         107.0        75.0    2210          14.4          81         0         1
60      36          6         250.0        88.0    3302          15.5          71         0         0
61     139          8         302.0       140.0    4638          16.0          74         0         0
62     290          8         351.0       142.0    4054          14.3          79         0         0
63     155          6         250.0        72.0    3158          19.5          75         0         0
64     194          6         232.0        90.0    3085          17.6          76         0         0
65     195          4          85.0        52.0    2035          22.2          76         0         0
66      59          4          97.0        54.0    2254          23.5          72         1         0
67     111          3          70.0        90.0    2124          13.5          73         0         1
68     219          4         122.0        96.0    2300          15.5          77         0         0
69     173          4         119.0        97.0    2545          17.0          75         0         1
70       6          8         454.0       220.0    4354           9.0          70         0         0
71     287          8         351.0       138.0    3955          13.2          79         0         0
72     274          5         131.0       103.0    2830          15.9          78         1         0
73     150          4         108.0        93.0    2391          15.5          74         0         1
74      10          8         383.0       170.0    3563          10.0          70         0         0
75     331          4          97.0        67.0    2145          18.0          80         0         1
76     103          8         400.0       150.0    4997          14.0          73         0         0
77      81          4          97.0        92.0    2288          17.0          72         0         1
78     227          6         225.0       100.0    3630          17.7          77         0         0
79     239          4          97.0        67.0    1985          16.4          77         0         1
80     299          4         141.0        71.0    3190          24.8          79         1         0
81     211          6         168.0       120.0    3820          16.7          76         1         0
82     167          4          97.0        75.0    2171          16.0          75         0         1
83     165          8         262.0       110.0    3221          13.5          75         0         0
84      89          8         318.0       150.0    3777          12.5          73         0         0
85     265          8         318.0       140.0    4080          13.7          78         0         0
86     163          6         225.0        95.0    3785          19.0          75         0         0
87     147          4          90.0        75.0    2108          15.5          74         1         0
88     283          6         232.0        90.0    3265          18.2          79         0         0
89      92          8         351.0       158.0    4363          13.0          73         0         0
90      69          8         350.0       160.0    4456          13.5          72         0         0
91     123          6         156.0       122.0    2807          13.5          73         0         1
92      96          8         360.0       175.0    3821          11.0          73         0         0
93     143          4          97.0        78.0    2300          14.5          74         1         0
94     302          4         105.0        70.0    2150          14.9          79         0         0
95      97          6         225.0       105.0    3121          16.5          73         0         0
96     228          6         250.0        98.0    3525          19.0          77         0         0
97      68          8         350.0       155.0    4502          13.5          72         0         0
98      23          4         121.0       113.0    2234          12.5          70         1         0
99      37          6         232.0       100.0    3288          15.5          71         0         0
100    144          4          76.0        52.0    1649          16.5          74         0         1
101    122          4         121.0       110.0    2660          14.0          73         1         0
102     67          8         429.0       208.0    4633          11.0          72         0         0
103    250          8         318.0       140.0    3735          13.2          78         0         0
104    357          4         119.0       100.0    2615          14.8          81         0         1
105    278          4          89.0        71.0    1990          14.9          78         1         0
106    316          6         225.0        90.0    3381          18.7          80         0         0
107    193          6         200.0        81.0    3012          17.6          76         0         0
108    125          6         198.0        95.0    3102          16.5          74         0         0
109    146          4          90.0        75.0    2125          14.5          74         0         0
110    233          4          97.0        78.0    1940          14.5          77         1         0
111     86          8         304.0       150.0    3672          11.5          73         0         0
112    335          4         122.0        88.0    2500          15.1          80         1         0
113    203          4          97.0        71.0    1825          12.2          76         1         0
114    336          4         140.0        92.0    2905          14.3          80         0         0
115    223          8         318.0       145.0    4140          13.7          77         0         0
116    258          6         231.0       105.0    3380          15.8          78         0         0
117    301          4         105.0        70.0    2200          13.2          79         0         0
118    183          4         116.0        81.0    2220          16.9          76         1         0
119    327          5         121.0        67.0    2950          19.9          80         1         0
120    282          4         140.0        88.0    2890          17.3          79         0         0
121    209          4         120.0        88.0    3270          21.9          76         1         0
122    281          6         200.0        85.0    2990          18.2          79         0         0
123    129          4          79.0        67.0    1950          19.0          74         0         1
124     38          8         350.0       165.0    4209          12.0          71         0         0
125     11          8         340.0       160.0    3609           8.0          70         0         0
126    326          4          90.0        48.0    2335          23.7          80         1         0
127    185          4          98.0        79.0    2255          17.7          76         0         0
128    220          4          85.0        70.0    1945          16.8          77         0         1
129    112          4         122.0        85.0    2310          18.5          73         0         0
130    179          4         121.0        98.0    2945          14.5          75         1         0
131    268          4         119.0        97.0    2300          14.7          78         0         1
132    333          6         168.0       132.0    2910          11.4          80         0         1
133    117          4          68.0        49.0    1867          19.5          73         1         0
134    366          6         225.0        85.0    3465          16.6          81         0         0
135    374          4         151.0        92.0    3035          20.5          82         0         0
136    382          4         108.0        70.0    2245          16.9          82         0         1
137    286          8         302.0       129.0    3725          13.4          79         0         0
138    360          6         145.0        76.0    3160          19.6          81         1         0
139    164          6         231.0       110.0    3039          15.0          75         0         0
140    385          4          91.0        67.0    1995          16.2          82         0         1
141    136          8         302.0       140.0    4141          14.0          74         0         0
142    154          6         250.0        72.0    3432          21.0          75         0         0
143    199          6         225.0       100.0    3651          17.7          76         0         0
144    197          4          90.0        70.0    1937          14.2          76         1         0
145    390          4         144.0        96.0    2665          13.9          82         0         1
146      2          8         318.0       150.0    3436          11.0          70         0         0
147    204          4          85.0        70.0    1990          17.0          76         0         1
148    115          8         350.0       145.0    4082          13.0          73         0         0
149    232          8         351.0       149.0    4335          14.5          77         0         0
150    369          4         112.0        88.0    2395          18.0          82         0         0
151     26          8         307.0       200.0    4376          15.0          70         0         0
152    120          4         121.0       112.0    2868          15.5          73         1         0
153    305          4         151.0        90.0    2670          16.0          79         0         0
154    224          8         302.0       130.0    4295          14.9          77         0         0
155    346          4          97.0        67.0    2065          17.8          81         0         1
156    266          4          98.0        68.0    2155          16.5          78         0         0
157    314          4         140.0        88.0    2870          18.1          80         0         0
158    342          4         135.0        84.0    2385          12.9          81         0         0
159    127          6         232.0       100.0    2901          16.0          74         0         0
160     74          8         302.0       140.0    4294          16.0          72         0         0
161    321          4         108.0        75.0    2265          15.2          80         0         1
162     29          4          97.0        88.0    2130          14.5          71         0         1
163     83          4          98.0        80.0    2164          15.0          72         0         0
164    329          4          91.0        67.0    1850          13.8          80         0         1
165    107          6         232.0       100.0    2789          15.0          73         0         0
166    247          4          85.0        70.0    2070          18.6          78         0         1
167    255          4         140.0        88.0    2720          15.4          78         0         0
168    133          6         250.0       100.0    3781          17.0          74         0         0
169    244          4          90.0        48.0    1985          21.5          78         1         0
170    184          4         140.0        92.0    2572          14.9          76         0         0
171    289          8         350.0       155.0    4360          14.9          79         0         0
172     44          8         400.0       175.0    5140          12.0          71         0         0
173    365          6         200.0        88.0    3060          17.1          81         0         0
174     65          8         351.0       153.0    4129          13.0          72         0         0
175    320          4         119.0        92.0    2434          15.0          80         0         1
176     85          8         350.0       175.0    4100          13.0          73         0         0
177    242          4         121.0       110.0    2600          12.8          77         1         0
178    186          4         101.0        83.0    2202          15.3          76         1         0
179    159          8         351.0       148.0    4657          13.5          75         0         0
180     12          8         400.0       150.0    3761           9.5          70         0         0
181     35          6         250.0       100.0    3329          15.5          71         0         0
182     28          8         304.0       193.0    4732          18.5          70         0         0
183    170          4         140.0        78.0    2592          18.5          75         0         0
184    142          4          79.0        67.0    1963          15.5          74         1         0
185    317          4          97.0        78.0    2188          15.8          80         1         0
186    271          4         156.0       105.0    2745          16.7          78         0         0
187    221          8         305.0       145.0    3880          12.5          77         0         0
188     95          8         455.0       225.0    4951          11.0          73         0         0
189     51          4          79.0        70.0    2074          19.5          71         1         0
190    240          4          97.0        78.0    2190          14.1          77         1         0
191    297          5         183.0        77.0    3530          20.1          79         1         0
192    325          4          90.0        48.0    2085          21.7          80         1         0
193    178          4         120.0        88.0    2957          17.0          75         1         0
194     41          8         318.0       150.0    4096          13.0          71         0         0

In [ ]:
# The following blocks split...for learning!
ohe= OneHotEncoder(sparse_output=False, drop='first')
origin_array= ohe.fit_transform(X_test[['origin']])
# get column names from sklearn
origin_array

In [17]:
origin_cols= ohe.get_feature_names_out(['origin'])
# build df from array
origin_cols

array(['origin_2', 'origin_3'], dtype=object)

In [18]:
df_origin = pd.DataFrame(origin_array, columns=origin_cols, dtype=int)
df_origin

    origin_2  origin_3
0          0         1
1          0         0
2          0         0
3          0         0
4          0         0
..       ...       ...
75         0         0
76         0         0
77         0         0
78         1         0
79         0         0

[80 rows x 2 columns]

In [20]:
X_test.drop(columns=['origin']).reset_index()

,index,cylinders,displacement,horsepower,weight,acceleration,model year
0,198,4,91.0,53.0,1795,17.4,76
1,396,4,120.0,79.0,2625,18.6,82
2,33,6,232.0,100.0,2634,13.0,71
3,208,8,318.0,150.0,3940,13.2,76
4,93,8,318.0,150.0,4237,14.5,73
...,...,...,...,...,...,...,...
75,249,8,260.0,110.0,3365,15.5,78
76,225,6,250.0,110.0,3520,16.4,77
77,367,4,112.0,88.0,2605,19.6,82
78,175,4,90.0,70.0,1937,14.0,75
79,285,8,305.0,130.0,3840,15.4,79

In [21]:
df=pd.concat([X_test.drop(columns=['origin']).reset_index(), df_origin], axis=1)
print(df)

    index  cylinders  displacement  horsepower  weight  acceleration  \
0     198          4          91.0        53.0    1795          17.4
1     396          4         120.0        79.0    2625          18.6
2      33          6         232.0       100.0    2634          13.0
3     208          8         318.0       150.0    3940          13.2
4      93          8         318.0       150.0    4237          14.5
..    ...        ...           ...         ...     ...           ...
75    249          8         260.0       110.0    3365          15.5
76    225          6         250.0       110.0    3520          16.4
77    367          4         112.0        88.0    2605          19.6
78    175          4          90.0        70.0    1937          14.0
79    285          8         305.0       130.0    3840          15.4

    model year  origin_2  origin_3
0           76         0         1
1           82         0         0
2           71         0         0
3           76         0         0
4           73         0         0
..         ...       ...       ...
75          78         0         0
76          77         0         0
77          82         0         0
78          75         1         0
79          79         0         0

[80 rows x 9 columns]

In the above code, we added drop='first' to drop origin 1 to avoid multicollinearity. It does not matter because the third answer is always implied by the other two responses.